multiple compiling issues resolved
1. from [here](https://stackoverflow.com/q/21738032/4999991) curly braces should be removed to solve the error:

> error: expected expression

2. from [here](https://stackoverflow.com/a/21739380/4999991) the error:

> error: too many arguments to function call, expected single argument '__x', have 2 arguments

should be resolved.

3. the error:

> error: no matching member function for call to 'build'

from the [cl::Program Class Reference](https://github.khronos.org/OpenCL-CLHPP/classcl_1_1_program.html) the `build` function requires `const vector< Device >` or `const char *options`